-- DB groupomania

PRAGMA foreign_keys = ON;

CREATE TABLE users (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NUll,
username VARCHAR(150) NOT NULL UNIQUE,
password VARCHAR(150) NOT NULL UNIQUE,
email VARCHAR(150) NOT NULL UNIQUE
);